[package]
name = "advent_of_code_19"
version = "0.1.0"
authors = ["Fabrizio Cirelli <fcirelli@sorint.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
